// GENERATED by scripts/fit-fog-value.mjs --write. Do not edit by hand.
//
// P(side to move wins) = σ(Σ beta[k] · feature[k]), the features as computed by
// src/fogFeatures.js (L = logit of Stockfish's expected score at depth 4,
// clipped to 0.0005). Model 'bal', fitted 2026-10-02 on 174246 positions
// from 2853 decisive games (fow-crawl-2026-08-06T17-38-19-279Z.json). Held-out log-loss of
// the result 0.5554 nats (base model 0.5665), against 1.0040 for
// Stockfish's own expected score and 0.6931 for the base rate (3-fold CV by game).

export const FOG_VALUE_MODEL = {
  depth: 4,
  clip: 0.0005,
  features: ['1', 'L', 'Lm', 'm', 'w', 'e', 'em', 'bal'],
  beta: [1.097122, 0.300115, -0.271895, -1.786912, -0.170468, -2.008292, 3.434134, 5.517986],
};
