// GENERATED by scripts/fit-fog-value.mjs --write. Do not edit by hand.
//
// P(side to move wins | Stockfish's expected score e at depth 4, material m/78,
// white to move) = σ(β₀ + β₁·L + β₂·L·m + β₃·m + β₄·w), L = logit(clip(e, 0.0005)).
// Fitted 2026-10-02 on 174246 positions from 2853 decisive games
// (fow-crawl-2026-08-06T17-38-19-279Z.json). Held-out log-loss of the result
// 0.5668 nats, against 1.0068 for Stockfish's own expected score
// and 0.6931 for the base rate (3-fold CV by game).

export const FOG_VALUE_MODEL = {
  depth: 4,
  clip: 0.0005,
  beta: [-0.073256, 0.292423, -0.117159, 0.051220, -0.142990],
};
